# @package _global_
# Redirect to global since need to modify model arguments
defaults:
  - default@datamodule
  - /optimizer@model: cifar10

datamodule:
  basic:
    name: cifar10
    input_size: 32

  data_module:
    _target_: pl_bolts.datamodules.CIFAR10DataModule
    data_dir: ${datamodule.basic.base_dir}
    shuffle: True
    pin_memory: True
    val_split: 5000

transform:
  train_transforms:
    # Augmentation options
    gaussian_blur_prob: 0.0
    solarize_prob: 0.0
    jitter_strength: 0.5
    global_asymmetric_trans: False
    # Global
    num_global_crops: 2
    global_input_size: ${datamodule.basic.input_size}
    global_scale: [ 0.08, 1.0 ]
    # Local
    num_local_crops: 0
    local_input_size: null
    local_scale: null
    normalize:
      _target_: pl_bolts.transforms.dataset_normalizations.cifar10_normalization

  val_transforms:
    normalize:
      _target_: pl_bolts.transforms.dataset_normalizations.cifar10_normalization

model:
  backbone:
    maxpool1: False
    first_conv: False
