basic:
  name: ???
  base_dir: /dev/shm
  input_size: ???
  # TODO modify num_classes input interface in utils
  num_classes: ???
  train_samples: ???
  ratio: 1.0

data_module:
  batch_size: ${basic.device_batch_size}
  num_workers: ${basic.num_workers}
