# @package _global_
defaults:
  - default@trainer
  - override /optimizer@model: linear_eval
  - override /callbacks: supervised

basic:
  stage: linear_eval
  model_class: arch.modules.supervised.SupervisedModel

model:
  basic:
    linear_eval: true
    ckpt_path: ${basic.pretrained}

transform:
  train_transforms:
    supervised: True
