# @package _global_

defaults:
  - fit_default@_global_
  - override /callbacks@_global_: supervised
  - override /optimizer@model: supervised

basic:
  name: supervised
  stage: ${.name}
  model_class: arch.modules.supervised.SupervisedModel

trainer:
  max_epochs: 100

model:
  basic:
    linear_eval: False
