defaults:
  - default@optimizer

# Ref: https://github.com/facebookresearch/swav
optimizer:
  _target_: pl_bolts.optimizers.lars.LARS
  momentum: 0.9
  weight_decay: 1e-6

basic:
  base_lr: 4.8
  eff_batch_size: 256
