defaults:
  - default@optimizer

optimizer:
  _target_: pl_bolts.optimizers.lars.LARS
  momentum: 0.9
  weight_decay: 1e-6
  lr: ${model.basic.base_lr} * math.sqrt(${model.basic.eff_batch_size})

basic:
  base_lr: 0.075
  eff_batch_size: 256
