# @package _global_
# defaults:
#   - _self_
#   - arch@_global_: ???
#   - logger: tensorboard
#   - callbacks: null
#   # >>> Take care of special resnet for CIFAR-10
#   - model: resnet18
#   - datamodule: ???
#   # <<<
#   - trainer: fit
basic:
  cwd: ${hydra:runtime.cwd}
  # ---- Deterministic ----
  seed: 666
  # ---- Arch ----
  name: ???
  # ---- Dataset ----
  device_batch_size: ???
  num_workers: 4 * ${.num_gpus}
  # ---- Train ----
  stage: ???
  num_gpus: 4
  log_postfix: "default"
  warmup_epochs: 10
  ckpt_foramt: ${basic.name}-${model.backbone.backbone}-${datamodule.basic.name}-{epoch:05d}-{step}
  pretrained: null
  resume: null

logger: null
callbacks: null
