checkpoint_saver:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  filename: ${basic.ckpt_foramt}
  period: 25

lr_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: 'step'

collapase_checker:
  _target_: callbacks.custom_callbacks.CheckCollapse

online_linear:
  _target_: callbacks.custom_callbacks.OnlineLinear
  num_features: ${model.basic.num_features}
  num_classes: ${datamodule.basic.num_classes}
  dataset: ${datamodule.basic.name}
