defaults:
  # ---- Default setting ----
  - ../common/base@_global_
  - ../common/datamodule/${datamodule}@_global_
  - ../common/model/${model}@_global_
  # Take care of linear eval model
  - _self_
  - ../common/trainer/${trainer}@_global_
  # ---- Model specific ----
  - model: resnet18
  # Import after stage to update resent config in Cifar
  - datamodule: normal
  - trainer: fit
  # Select according to datamodule or manual specify
  - optional optimizer@_global_: null

name: simsiam
model:
  _target_: arch.modules.simsiam.SimSiamModel
