defaults:
  - base
  - _self_
  - logger: default
  - callbacks: null
  - transform: simclr
  # >>> Take care of special resnet for CIFAR-10
  - model: resnet18
  - datamodule: ???
  # <<<
  - trainer: fit

basic:
  # ---- Arch ----
  name: barlow_twins
  model_class: arch.modules.barlow_twins.BarlowTwinsModel

# Ref: https://github.com/facebookresearch/barlowtwins/blob/main/main.py
model:
  basic:
    # Original paper
    # lambda_: 0.0051
    # 1 / 128 in HSIC: https://arxiv.org/pdf/2104.13712.pdf
    lambda_: 0.0078125

hydra:
  searchpath:
    - pkg://configs/barlow_twins
