# @package _global_
basic:
  cwd: ${hydra:runtime.cwd}
  # ---- Deterministic ----
  seed: 666
  # ---- Arch ----
  name: ???
  # ---- Dataset ----
  device_batch_size: ???
  num_workers: 4 * ${.num_gpus}
  # ---- Train ----
  stage: ???
  num_gpus: 4
  log_postfix: "default"
  warmup_epochs: 10
  ckpt_foramt: ${basic.name}-${model.backbone.backbone}-${datamodule.basic.name}-{epoch:05d}-{step}
  ckpt_base_dir: ${basic.cwd}/log/${basic.name}
  pretrained: null
  resume: null

logger: null
callbacks: null
