defaults:
  - base
  - _self_
  - logger: default
  - callbacks: null
  - transform: byol
  # >>> Take care of special resnet for CIFAR-10
  - model: resnet18
  - datamodule: ???
  # <<<
  - trainer: fit

basic:
  # ---- Arch ----
  name: byol
  model_class: arch.modules.byol.BYOLModel

hydra:
  searchpath:
    - pkg://configs/byol
