defaults:
  - base
  - _self_
  - logger: default
  - callbacks: null
  # >>> Take care of special resnet for CIFAR-10
  - model: resnet18
  - datamodule: ???
  # <<<
  - trainer: fit

basic:
  # ---- Arch ----
  name: dino
  model_class: arch.modules.dino.DINOModel

model:
  basic:
    target_temp: 0.04
    online_temp: 0.1
    center_momentum: 0.9

hydra:
  searchpath:
    - pkg://configs/dino
