defaults:
  - base
  - _self_
  - logger: default
  - callbacks: null
  # >>> Take care of special resnet for CIFAR-10
  - model: resnet18
  - datamodule: ???
  # <<<
  - trainer: fit

basic:
  # ---- Arch ----
  name: moco
  model_class: arch.modules.moco.MOCOModel

model:
  basic:
    temperature: 0.07
    bank_size: 65536
    tau: 0.999

hydra:
  searchpath:
    - pkg://configs/moco
