defaults:
  - base
  - _self_
  - logger: default
  - callbacks: null
  - transform: simclr
  # >>> Take care of special resnet for CIFAR-10
  - model: resnet18
  - datamodule: ???
  # <<<
  - trainer: fit

basic:
  # ---- Arch ----
  name: moco
  model_class: arch.modules.moco.MOCOModel

model:
  basic:
    bank_size: 65536
    # TODO Ablation on tau and temperature
    # ImageNet setting
    # tau: 0.999
    # temperature: 0.07
    # Cifar setting, good result on food11
    tau: 0.99
    temperature: 0.1

hydra:
  searchpath:
    - pkg://configs/moco
