defaults:
  - base
  - _self_
  - logger: default
  - callbacks: null
  - transform: dino
  # >>> Take care of special resnet for CIFAR-10
  - model: resnet18
  - datamodule: ???
  # <<<
  - trainer: fit

basic:
  # ---- Arch ----
  name: sim_estimator
  model_class: arch.modules.sim_estimator.SimEstimatorModel

hydra:
  searchpath:
    - pkg://configs/sim_estimator
