# @package _gloabl_

callbacks:
  lr_monitor:
    _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: 'step'

  collapase_checker:
    _target_: callbacks.custom_callbacks.CheckCollapse

  online_linear:
    _target_: callbacks.custom_callbacks.OnlineLinear
    num_features: ${basic.num_features}
    num_classes: ${model.num_classes}
    dataset: ${datamodule.dataset}
