defaults:
  - default@optimizer

# Ref: https://github.com/facebookresearch/moco/blob/master/main_lincls.py
optimizer:
  _target_: torch.optim.SGD
  momentum: 0.9
  weight_decay: 0

basic:
  base_lr: 30.0
  eff_batch_size: 256
