defaults:
  - default@optimizer

# BarlowTwins paper
optimizer:
  _target_: torch.optim.SGD
  momentum: 0.9
  weight_decay: 1e-6

basic:
  # lr = 0.3 in the BarlowTwins paper
  # lr = 0.1 in its GitHub repo, using in the eval phase
  base_lr: 0.3
  eff_batch_size: 256
