defaults:
  - default@optimizer

optimizer:
  _target_: pl_bolts.optimizers.lars.LARS
  momentum: 0.9
  weight_decay: 1e-6
  lr: ${model.basic.base_lr} * math.sqrt(${model.basic.eff_batch_size})

basic:
  # 4096 in original paper(LARS, base_lr=0.3)
  # 128 in pl_bolts(LARS, lr=1e-3)
  # 256 in lightly(SGD, lr=0.1)
  base_lr: 0.075
  eff_batch_size: 256
  # 1 / 128 in HSIC: https://arxiv.org/pdf/2104.13712.pdf
  lambda_: 0.0078125

mlp:
  # ResNet18
  proj_hidden_dim: 512
  pred_hidden_dim: 0
  out_dim: 128
  num_proj_mlp_layer: 2
  proj_last_bn: False
  using_predictor: False
