defaults:
  - default@optimizer

optimizer:
  _target_: pl_bolts.optimizers.lars.LARS
  momentum: 0.9
  weight_decay: 1e-4

basic:
  # 1024 in original paper(LARS, base_lr=[0.5, 1.0, 1.5])
  # 128 in pl_bolts(LARS, lr=1e-3)
  # 256 in lightly(SGD, lr=0.1)
  # 512 in github(LARS lr=1.0)
  base_lr: 1.0
  eff_batch_size: 512
  temperature: 0.5
