base: &base
  basic:
    warm_up_epochs: 10
  model: &model
    # bs = 256/512 performs best in paper(ResNet50)
    eff_batch_size: 512
    maxpool1: True
    first_conv: True
    momentum: 0.9

    # TODO: add LARS & min lr for BT
    # Adam && bolts default
    # optimizer: adam
    # base_lr: 1e-3
    # weight_decay: 1.5e-6
    # SGD
    # NOTE 2048 -> 0.2 lr; 512 -> 0.05?
    optimizer: sgd
    base_lr: 0.2
    weight_decay: 1.5e-6
    # LARS
    # base_lr: 0.2

  trainer:
    max_epochs: 800
    distributed_backend: 'ddp'

  # Cifar
  # NOTE hyperparameters from lightly
  cifar:
    maxpool1: False
    first_conv: False
    optimizer: sgd
    base_lr: 1e-3
    weight_decay: 5e-4

# Complete exactly as BYOL paper & bolts
resnet18: &resnet18
  <<: *base
  model:
    <<: *model
    mlp_config:
      proj_hidden_dim: 8192
      pred_hidden_dim: 0
      out_dim: 8192
      num_proj_mlp_layer: 3
      proj_last_bn: False
      using_predictor: False

resnet50:
  <<: *resnet18
