base: &base
  basic:
    warm_up_epochs: 10
  model: &model
    base_lr: 1e-3
    weight_decay: 5e-4
    momentum: 0.9
    # bs = 256/512 performs best in paper(ResNet50)
    eff_batch_size: 512
  trainer:
    max_epochs: 800
    distributed_backend: 'ddp'

resnet18:
  <<: *base
  model:
    <<: *model
    mlp_config:
      proj_hidden_dim: 8192
      out_dim: 8192
      num_proj_layers: 3

resnet50:
  <<: *base
  model:
    <<: *model
    mlp_config:
      proj_hidden_dim: 8192
      out_dim: 8192
      num_proj_layers: 3
