base: &base
  basic:
    warm_up_epochs: 10
  model: &model
    # bs = 256/512 performs best in paper(ResNet50)
    maxpool1: True
    first_conv: True
    momentum: 0.9

    # # --->Adam && bolts default
    # optimizer: adam
    # base_lr: 1e-3
    # weight_decay: 1.5e-6
    # # ---> LARS: BYOL paper
    # optimizer: lars
    # base_lr: 0.4
    # weight_decay: 1.5e-6
    # eff_batch_size: 512
    # # ---> LARS: BYOL TWCC exp
    optimizer: lars
    base_lr: 2.0
    weight_decay: 1e-6
    # eff_batch_size: 256
    eff_batch_size: 512
    # # --->SGD: SimSiam
    # optimizer: sgd
    # base_lr: 0.4
    # weight_decay: 1e-6
    # eff_batch_size: 512

  trainer:
    max_epochs: 1000
    distributed_backend: 'ddp'

  # Cifar
  cifar:
    maxpool1: False
    first_conv: False
    eff_batch_size: 512

# Complete exactly as BYOL paper & bolts
resnet18: &resnet18
  <<: *base
  model:
    <<: *model
    mlp_config:
      proj_hidden_dim: 4096
      pred_hidden_dim: 4096
      out_dim: 256
      num_proj_mlp_layer: 2
      proj_last_bn: False
      using_predictor: True

resnet50:
  <<: *resnet18
