base: &base
  basic:
    warm_up_epochs: 10
  model: &model
    # eff_batch_size is adaptive in get_config()
    momentum: 0.9
    # ----------------
    # Adam && bolts default
    # TODO Check sgd parameters in SimSiam paper
    # optimizer: adam
    # base_lr: 1e-3
    # weight_decay: 1e-6
    # ----------------
    # SGD
    optimizer: sgd
    base_lr: 30
    weight_decay: 0
  cifar:
    optimizer: sgd
    base_lr: 30
    weight_decay: 0

  trainer:
    max_epochs: 90
    distributed_backend: 'ddp'
    check_val_every_n_epoch: 8
