base: &base
  basic:
    warm_up_epochs: 10
  model: &model
    base_lr: 1e-3
    weight_decay: 1.5e-6
    momentum: 0.9
    # bs = 256/512 performs best in paper(ResNet50)
    eff_batch_size: 512
  trainer:
    max_epochs: 1000
    distributed_backend: 'ddp'

# ---- Lightning bolts ----
resnet18:
  <<: *base
  model:
    <<: *model
    mlp_config:
      proj_hidden_dim: 1024
      pred_hidden_dim: 1024
      out_dim: 128
      # proj_hidden_dim: 512
      # pred_hidden_dim: 512
      # out_dim: 64
      num_proj_layers: 2

resnet50:
  <<: *base
  model:
    <<: *model
    mlp_config:
      proj_hidden_dim: 2048
      pred_hidden_dim: 2048
      out_dim: 128
      num_proj_layers: 2

# ---- Lightly & original paper ----
# resnet18:
#   <<: *base
#   model:
#     <<: *model
#     mlp_config:
#       proj_hidden_dim: 512
#       pred_hidden_dim: 128
#       out_dim: 512
#       num_proj_layers: 2
#
# resnet50:
#   <<: *base
#   model:
#     <<: *model
#     mlp_config:
#       proj_hidden_dim: 2048
#       pred_hidden_dim: 512
#       out_dim: 2048
#       num_proj_layers: 3
