base: &base
  basic:
    warm_up_epochs: 10
  model: &model
    # bs = 256/512 performs best in paper(ResNet50)
    eff_batch_size: 512
    maxpool1: True
    first_conv: True
    momentum: 0.9

    # # Adam && bolts default
    # optimizer: adam
    # base_lr: 1e-3
    # weight_decay: 1e-6
    # # SGD
    # optimizer: sgd
    # base_lr: 0.05
    # weight_decay: 1e-4

    # Cifar
    optimizer: sgd
    base_lr: 0.03
    weight_decay: 5e-4
    eff_batch_size: 512

  trainer:
    max_epochs: 800
    distributed_backend: 'ddp'

# # ---- Lightning bolts ----
# resnet18:
#   <<: *base
#   model:
#     <<: *model
#     mlp_config:
#       proj_hidden_dim: 2048
#       pred_hidden_dim: 2048
#       out_dim: 128
#       num_proj_mlp_layer: 2
#       proj_last_bn: False
#       using_predictor: True
#
# resnet50:
#   <<: *base
#   model:
#     <<: *model
#     mlp_config:
#       proj_hidden_dim: 2048
#       pred_hidden_dim: 2048
#       out_dim: 128
#       num_proj_mlp_layer: 2
#       proj_last_bn: False
#       using_predictor: True

# ---- Lightly & original paper ----
resnet18:
  <<: *base
  model:
    <<: *model
    mlp_config:
      # Only proj_hidden_dim is uncertained
      proj_hidden_dim: 512
      pred_hidden_dim: 512
      out_dim: 2048
      num_proj_mlp_layer: 2
      # ImageNet Linear Eval: w/ BN: 68.1, w/o BN: 67.4
      proj_last_bn: True
      using_predictor: True

resnet50:
  <<: *base
  model:
    <<: *model
    mlp_config:
      proj_hidden_dim: 2048
      pred_hidden_dim: 512
      out_dim: 2048
      num_proj_mlp_layer: 3
      proj_last_bn: True
      using_predictor: True
