defaults:
  - default@optimizer

# LARS: BYOL paper
optimizer:
  _target_: pl_bolts.optimizers.lars.LARS
  momentum: 0.9
  weight_decay: 1.5e-6
  trust_coefficient: 0.001

basic:
  # NOTE: This base_lr may only be suitable for ImageNet, underfitting in Food11
  base_lr: 0.4
  eff_batch_size: 512
