_target_: ${basic.model_class}

basic:
  num_classes: ${datamodule.basic.num_classes}
  base_lr: ${basic.base_lr}
  eff_batch_size: ${basic.eff_batch_size}
  num_global_crops: ${transform.train_transforms.num_global_crops}
  num_local_crops: ${transform.train_transforms.num_local_crops}

scheduler:
  max_steps: ???
  warmup_steps: ???
  start_lr: 0.0
  end_lr: 0.0

backbone:
  first_conv: True
  maxpool1: True

mlp: null
