# @package _global_
datamodule:
  dataset_name: ???
  basic:
    base_dir: /dev/shm
    input_size: ???

  data_module:
    batch_size: ${general.device_batch_size}
    num_workers: ${general.num_workers}

  train_transforms:
    _target_: pl_bolts.models.self_supervised.simclr.SimCLRTrainDataTransform
    input_height: ${datamodule.basic.input_size}

  val_transforms:
    _target_: pl_bolts.models.self_supervised.simclr.SimCLREvalDataTransform
    input_height: ${datamodule.basic.input_size}

model:
  maxpool1: True
  first_conv: True
