# @package _global_
defaults:
  - default@trainer
  - override /optimizer@model: linear_eval

model:
  basic:
    ckpt_path: ${basic.pretrained}
  _target_: arch.modules.linear_eval.LinearEvalModel

basic:
  stage: linear_eval
